openapi: 3.0.3
info:
  title: Related Tags Documentation
  description: These endpoints requires authentication. Its purpose is to manage related tags items.
  contact:
    email: play@empathy.co
  version: '1.0.0'
servers:
  - url: 'http://localhost:8080'
    description: local
  - url: 'https://play-api.kroger.internal.dataless.gcp.empathy.dev/'
    description: kroger dataless
  - url: 'https://play-api.carrefour.internal.dataless.gcp.empathy.dev/'
    description: carrefour dataless

security:
  - BearerAuth: []

paths:
  /{requestInstanceId}/search/tooling/related_tags:
    get:
      tags:
        - Related tags
      summary: Returns related tags items for the given instance.
      operationId: getAll
      parameters:
        - name: requestInstanceId
          in: path
          description: Instance identifier.
          required: true
          style: simple
          schema:
            type: string
        - name: start
          in: query
          description: Number of items to skip.
          required: true
          schema:
            type: string
            default: 0
        - name: rows
          in: query
          description: Number of items to be returned.
          required: true
          schema:
            type: integer
            default: 20
        - name: context.lang
          in: query
          description: Language associated with the different tags. To filter by this parameter, the context.query parameter is also required.
          required: false
          schema:
            type: string
        - name: context.query
          in: query
          description: Query associated with the different tags. To filter by this parameter, the context.lang parameter is also required.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedTagResultList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      tags:
        - Related tags
      summary: Create a new related tag for the given instance and id.
      operationId: post
      parameters:
        - name: requestInstanceId
          in: path
          description: Identifier of the instance.
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersistsRelatedTag'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedTags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /{requestInstanceId}/search/tooling/related_tags/{id}:
    get:
      tags:
        - Related tags
      summary: Return a related tag item for the given instance and id.
      operationId: getById
      parameters:
        - name: requestInstanceId
          in: path
          description: Identifier of the instance.
          required: true
          style: simple
          schema:
            type: string
        - name: id
          in: path
          description: Identifier of the related tag.
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedTags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      tags:
        - Related tags
      summary: Update a related tag for the given instance and id.
      operationId: put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersistsRelatedTag'
      parameters:
        - name: requestInstanceId
          in: path
          description: Identifier of the instance.
          required: true
          style: simple
          schema:
            type: string
        - name: id
          in: path
          description: Identifier of the related tag.
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedTags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      tags:
        - Related tags
      summary: Remove a related tag for the given instance and id.
      operationId: delete
      parameters:
        - name: requestInstanceId
          in: path
          description: Identifier of the instance.
          required: true
          style: simple
          schema:
            type: string
        - name: id
          in: path
          description: Identifier of the related tag.
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedTags'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    RelatedTagResultList:
      title: RelatedTagList
      description: Result list of related tags.
      type: object
      properties:
        num_found:
          description: Number of related tags found.
          type: integer
        results:
          description: List of related tags.
          type: array
          items:
            $ref: '#/components/schemas/RelatedTags'
    RelatedTags:
      title: Related Tag
      description: Related tag item definition.
      required:
        - enabled
      type: object
      properties:
        id:
          description: Related tag identifier.
          type: string
        enabled:
          description: Related tag status.
          type: boolean
        context:
          $ref: '#/components/schemas/Context'
        metadata:
          $ref: '#/components/schemas/Metadata'
        tags:
          $ref: '#/components/schemas/Tags'
    Context:
      title: Context
      description: Define the properties where the configuration will be applied.
      required:
        - query
        - lang
      type: object
      properties:
        query:
          description: Query associated with the different tags.
          type: string
        lang:
          description: Language associated with the different tags.
          type: string
    Metadata:
      title: Metadata
      description: Stores information about the configuration itself.
      type: object
      properties:
        created_on:
          description: When was created.
          type: string
          example: 'yyyy-MM-dd''T''HH:mm:ss''Z'''
        updated_on:
          type: string
          description: When was updated.
          example: 'yyyy-MM-dd''T''HH:mm:ss''Z'''
        user:
          description: User who created or modified a related tag.
          type: string
    Tags:
      title: Tags
      description: Contains all the related tags.
      required:
        - rules
      type: object
      properties:
        indexed:
          $ref: '#/components/schemas/Indexed'
        rules:
          $ref: '#/components/schemas/Rules'
    Indexed:
      title: Indexed
      description: List of related tags of the system.
      type: array
      items:
        type: object
        properties:
          tag:
            description: Related tag name.
            type: string
          query:
            description: Query associated to the tag.
            type: string
    Rules:
      title: Rules
      description: Properties for new related tags that includes rules for adding, modifying and removing tags to change the system behavior.
      type: array
      items:
        type: object
        properties:
          tag:
            description: Related tag name.
            type: string
          query:
            description: Query associated to the tag.
            type: string
          id:
            description: Related tag identifier.
            type: string
          type:
            description: Related tag action.
            type: string
            enum:
              - add
              - edit
              - remove
          original_query:
            description: The first query that was assigned to the related tag.
            type: string
    PersistsRelatedTag:
      title: Body
      description: Body to modify a related tag.
      required:
        - enabled
        - context
        - tags
      type: object
      properties:
        enabled:
          description: Related tag status.
          type: boolean
        context:
          $ref: '#/components/schemas/Context'
        tags:
          type: object
          properties:
            tag:
              description: Related tag name.
              type: string
            query:
              description: Query associated to the tag.
              type: string
            original_query:
              description: The first query for the tag.
              type: string
            type:
              description: Related tag action.
              type: string
              enum:
                - add
                - edit
                - remove
    BadRequest:
      title: Bad Request
      type: object
      properties:
        timestamp:
          type: string
          example: "2021-03-31T12:41:28.293+00:00"
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        details:
          type: object
          properties:
            id:
              type: string
            message:
              type: string
    Unauthorized:
      title: Unautorized
      type: object
      properties:
        timestamp:
          type: string
          example: "2021-03-31T12:41:28.293+00:00"
        status:
          type: integer
          example: 401
        error:
          type: string
          example: UNAUTHORIZED
        details:
          type: object
          properties:
            id:
              type: string
              example: UNAUTHORIZED
            message:
              type: string
              example: Full authentication is required to access this resource
    Forbidden:
      title: Forbidden
      type: object
      properties:
        timestamp:
          type: string
          example: "2021-03-31T12:41:28.293+00:00"
        status:
          type: integer
          example: 403
        error:
          type: string
          example: FORBIDDEN
        details:
          type: object
          properties:
            id:
              type: string
              example: FORBIDDEN
            message:
              type: string
              example: Access is denied
    InternalServerError:
      title: Internal Server Error
      type: object
      properties:
        timestamp:
          type: string
          example: "2021-03-31T12:41:28.293+00:00"
        status:
          type: integer
          example: 500
        error:
          type: string
          example: Internal Server Error
        details:
          type: object
          properties:
            id:
              type: string
            message:
              type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT