openapi: 3.0.3
info:
  title: Status Endpoint
  description: The objective of this endpoint is exposed the status of the play service.
  contact:
    email: play@empathy.co
  version: '1.0.0'
servers:
  - url: 'http://localhost:8080'
    description: local
  - url: 'https://play-api.kroger.internal.dataless.gcp.empathy.dev/'
    description: kroger dataless
  - url: 'https://play-api.carrefour.internal.dataless.gcp.empathy.dev/'
    description: carrefour dataless
tags:
  - name: status
    description: Service Status
paths:
  /status/health:
    get:
      tags:
        - status
      summary: Endpoint to check the availability of the service.
      operationId: health
      responses:
        '200':
          description: OK
  /status/info:
    get:
      tags:
        - status
      summary: Returns the information about the project.
      operationId: environment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
components:
  schemas:
    Info:
      title: Info
      type: object
      properties:
        build.time:
          type: string
          example: "2020-08-07 07:54:28"
          description: When was it last built.
        project.version:
          type: string
          example: "1.4.0"
          description: Version that is deployed.
    NotFound:
      title: NotFound
      type: object
      properties:
        timestamp:
          type: string
          example: 2020-09-09T06:43:01.899+0000
          description: Datetime of the request.
        status:
          type: string
          example: 404
          description: HTTP status code of the request.
        error:
          type: string
          example: NOT_FOUND
          description: HTTP status identifier.
        details:
          type: object
          description: Specific details of the error.
          properties:
            id:
              type: string
              example: NOT_FOUND
              description: Error identifier.
            message:
              type: string
              example: Not found
              description: Description of the error.


