openapi: 3.0.1
info:
  title: Beacon API
  description: Beacon - Obtain your Next Queries and Related Tags from here!
  version: 0.5.13
paths:
  /nextqueries/{instance}:
    get:
      tags:
      - public
      summary: |-
        Retrieves the sorted merged data of curated and indexed next queries and wraps the reponse object List<NextQuery> in a
         NextQueriesResponse.
      description: url.../nextqueries/empathy?lang=en&query=shirt
      operationId: getMergedNextQueries
      parameters:
      - name: instance
        in: path
        required: true
        schema:
          type: string
      - name: lang
        in: query
        required: true
        schema:
          type: string
      - name: query
        in: query
        required: true
        schema:
          type: string
      - name: division
        in: query
        required: false
        schema:
          type: string
      - name: store
        in: query
        required: false
        schema:
          type: string
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: "Example response:\n \t\"status\": 200,\n \t\"data\": \t\t\"\
            nextqueries\": [\n \t          \t\t\t\t\"query\": \"boots\", //Next query\n\
            \ \t\t\t\t\"position\": 0,  //position in the curated list\n \t\t\t\t\"\
            source\": \"CURATED\" //type of NQ, CURATED: created by tooling via Playboard\n\
            \            ,\t\t\t\t\"query\": \"backpack\",\n \t\t\t\t\"position\"\
            : 1000,\n \t\t\t\t\"source\": \"ORGANIC\" //type of NQ, ORGANIC: created\
            \ based on wisdom of the crowd\n            \n \t\t]"
          content:
            application/json:
              schema:
                type: string
  /relatedtags/{instance}:
    get:
      tags:
      - public
      summary: |-
        Retrieves the sorted merged data of curated and indexed related tags and wraps the response object
         List<RelatedTag> in a RelatedTagResponse.
      description: url.../nextqueries/empathy?lang=en&query=shirt
      operationId: getMergedRelatedTags
      parameters:
      - name: instance
        in: path
        required: true
        schema:
          type: string
      - name: lang
        in: query
        required: true
        schema:
          type: string
      - name: query
        in: query
        required: true
        schema:
          type: string
      - name: division
        in: query
        required: false
        schema:
          type: string
      - name: store
        in: query
        required: false
        schema:
          type: string
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: "Example response:\n \t\"status\": 200,\n \t\"data\": \t\t\"\
            relatedtags\": [\n \t         \t\t\t\t\"query\": \"shoes night\", //Full\
            \ query, given query + tag\n \t\t\t\t\"tag\": \"night\", //Only tag\n\
            \ \t\t\t\t\"position\": 0, //position in the curated list\n \t\t\t\t\"\
            source\": \"CURATED\" //type of tag, CURATED: created by tooling via Playboard\n\
            \           ,\t\t\t\t\"query\": \"brown shoes\",\n \t\t\t\t\"tag\": \"\
            brown\",\n \t\t\t\t\"position\": 1,\n \t\t\t\t\"source\": \"ORGANIC\"\
            \ //type of tag, ORGANIC: created based on wisdom of the crowd\n     \
            \       \n \t\t]"
          content:
            application/json:
              schema:
                type: string
